import { redirect } from 'next/navigation';
import { getQueueAnnounceEnabled } from '@dialeros/control-plane';
import { getCurrentUser } from '@/lib/session';
import { QueueAnnounceToggle } from './toggle';

export const dynamic = 'force-dynamic';

// Iter 177 — Queue position announce settings page. Admin only.
// Single boolean toggle controlling whether the FS Lua hold-queue
// loop speaks the caller's position + ETA via the `say` engine
// (no extra audio install required).

export default async function QueueAnnouncePage() {
  const me = await getCurrentUser();
  if (!me) redirect('/login');
  if (me.role !== 'admin') {
    return (
      <div>
        <h1 className="text-2xl font-semibold mb-2">
          Queue position announcement
        </h1>
        <p className="text-error text-sm">Admin role required.</p>
      </div>
    );
  }

  const enabled = getQueueAnnounceEnabled();

  return (
    <div className="max-w-2xl">
      <h1 className="text-2xl font-semibold mb-1">
        Queue position announcement
      </h1>
      <p className="text-fg-subtle text-sm mb-6">
        When enabled, callers parked in an inbound hold queue
        will hear their current position in line and an estimated
        wait time. Announcements fire on the first poll where
        we know the position, again whenever the position
        changes (someone ahead gets answered or abandons), and
        as a heartbeat reassurance every 60 seconds. The ETA is
        derived from a rolling 30-minute average of recent
        dispatched waits on the same in-group, with a 30-second
        fallback for cold starts. Speech is generated by
        FreeSWITCH&apos;s built-in `say` engine — no extra audio
        files needed. Off by default; opt in here.
      </p>
      <QueueAnnounceToggle initialEnabled={enabled} />
    </div>
  );
}
