import Link from 'next/link';
import { redirect } from 'next/navigation';
import { getCurrentUser } from '@/lib/session';
import { COLUMN_MIGRATIONS } from '@dialeros/control-plane';

export const dynamic = 'force-dynamic';

// Iter 184 — Database backend status page. Read-only. Surfaces
// the configured DIALEROS_DB_BACKEND env var + DATABASE_URL
// (host masked) + applied-migration count. Today only sqlite is
// fully wired; pg arrives in iter 188 (pre-1.0). Until then
// operators export their sqlite via scripts/export-to-postgres.ts.

function maskDatabaseUrl(u: string | undefined): string {
  if (!u) return '(unset)';
  try {
    const parsed = new URL(u);
    if (parsed.password) parsed.password = '***';
    return parsed.toString();
  } catch {
    return '(invalid)';
  }
}

export default async function DatabaseSettingsPage() {
  const me = await getCurrentUser();
  if (!me) redirect('/login');
  if (me.role !== 'admin') {
    return (
      <div>
        <h1 className="text-2xl font-semibold mb-2">Database</h1>
        <p className="text-error text-sm">Admin role required.</p>
      </div>
    );
  }
  const backend =
    (process.env.DIALEROS_DB_BACKEND as 'sqlite' | 'postgres') ?? 'sqlite';
  const dbUrl = process.env.DATABASE_URL;
  const migrationCount = COLUMN_MIGRATIONS.length;
  const dbPath =
    process.env.DIALEROS_DB ?? '/opt/dialeros/apps/admin-gui/data/dialeros.db';

  return (
    <div className="max-w-3xl">
      <h1 className="text-2xl font-semibold mb-1">Database</h1>
      <p className="text-fg-subtle text-sm mb-6">
        Backend status + Postgres migration tooling. Today
        DialerOS runs on sqlite via{' '}
        <span className="font-mono">node:sqlite</span>; the
        Postgres query backend is groundwork for iter 188 (pre-1.0
        release). The export tool below works today — point it at
        your sqlite file, redirect to a .sql file, and{' '}
        <span className="font-mono">psql -f</span> against your
        target pg server.
      </p>

      <div className="border border-border rounded p-4 bg-card space-y-3 mb-6">
        <div>
          <span className="text-xs text-fg-subtle uppercase tracking-wider">
            Configured backend
          </span>
          <div className="text-lg font-semibold">
            {backend}
            {backend === 'postgres' ? (
              <span className="ml-2 text-xs text-warn">
                (groundwork — queries still route to sqlite until iter 188)
              </span>
            ) : null}
          </div>
        </div>
        <div>
          <span className="text-xs text-fg-subtle uppercase tracking-wider">
            sqlite path
          </span>
          <div className="font-mono text-sm">{dbPath}</div>
        </div>
        <div>
          <span className="text-xs text-fg-subtle uppercase tracking-wider">
            DATABASE_URL
          </span>
          <div className="font-mono text-sm">{maskDatabaseUrl(dbUrl)}</div>
        </div>
        <div>
          <span className="text-xs text-fg-subtle uppercase tracking-wider">
            Applied COLUMN_MIGRATIONS
          </span>
          <div className="text-sm tabular-nums">{migrationCount}</div>
        </div>
      </div>

      <h2 className="text-sm font-semibold mb-2">
        Export sqlite → Postgres
      </h2>
      <pre className="text-xs bg-card border border-border rounded p-3 overflow-x-auto mb-3">
{`# On the VPS, as the dialeros user:
cd /opt/dialeros
node --experimental-strip-types scripts/export-to-postgres.ts > /tmp/dialeros-pg-dump.sql

# Inspect:
less /tmp/dialeros-pg-dump.sql

# Apply to your target Postgres:
psql "\$DATABASE_URL" -f /tmp/dialeros-pg-dump.sql`}
      </pre>
      <p className="text-xs text-fg-subtle mb-6">
        The dump translates:
      </p>
      <ul className="text-xs text-fg-subtle list-disc list-inside space-y-1 mb-6">
        <li>
          <span className="font-mono">INTEGER PRIMARY KEY AUTOINCREMENT</span>{' '}
          → <span className="font-mono">GENERATED BY DEFAULT AS IDENTITY</span>
        </li>
        <li>
          <span className="font-mono">strftime('%Y-%m-%dT%H:%M:%fZ','now')</span>{' '}
          →{' '}
          <span className="font-mono">
            to_char(now() AT TIME ZONE 'UTC', …)
          </span>
        </li>
        <li>
          <span className="font-mono">datetime('now', '-N minutes')</span>{' '}
          →{' '}
          <span className="font-mono">now() - interval 'N minutes'</span>
        </li>
        <li>
          <span className="font-mono">INSERT OR IGNORE</span> → handled per
          statement (passthrough when in COLUMN_MIGRATIONS seeds)
        </li>
      </ul>
      <p className="text-xs text-fg-subtle mb-6">
        <strong>What doesn&apos;t translate:</strong> the FTS5
        virtual table (
        <span className="font-mono">dial_intents_fts</span>) is
        marked as a TODO comment in the dump. After import you
        need to add pg-native tsvector columns + GIN index for
        transcript search. Iter 188 wires this end-to-end.
      </p>

      <p className="text-xs text-fg-subtle">
        Health endpoint reports the active backend at{' '}
        <Link href="/api/health" className="text-link hover:underline">
          /api/health
        </Link>
        .
      </p>
    </div>
  );
}
