// Iter 184 — Pure SQL translator: sqlite → postgres.
//
// Closes Phase F's "Postgres option" by giving operators a one-shot
// path to migrate a live sqlite deployment to postgres without
// hand-editing the schema. The actual production pg query
// backend is groundwork for iter 188 (pre-1.0); this iter ships
// the *export tool* + status surface so any operator who wants
// to run pg can dump their sqlite to a pg-compatible .sql file.
//
// The translator is pure: takes a sqlite SQL statement (CREATE
// TABLE / CREATE INDEX / INSERT) and emits the postgres
// equivalent. No DB access. Trivially unit-testable.
//
// Coverage:
//   - sqlite types → pg types
//   - PRIMARY KEY AUTOINCREMENT → SERIAL / GENERATED IDENTITY
//   - INTEGER (used as bool) → preserved as INTEGER for value-fidelity
//     (DialerOS stores 0/1 explicitly; converting to BOOLEAN would
//     break every WHERE flag = 1 query)
//   - INSERT OR IGNORE → INSERT ... ON CONFLICT DO NOTHING
//   - INSERT OR REPLACE → INSERT ... ON CONFLICT DO UPDATE
//   - strftime('%Y-%m-%dT%H:%M:%fZ','now') →
//       to_char(now() AT TIME ZONE 'UTC',
//               'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
//   - CURRENT_TIMESTAMP → CURRENT_TIMESTAMP (same)
//   - datetime('now', '-N minutes/hours') →
//       now() - interval 'N minutes/hours'
//   - Partial indexes WHERE clause: passthrough (same syntax)
//   - FTS5 virtual tables: NOT TRANSLATED — emitted as a
//     placeholder comment + a TODO note (pg has its own FTS via
//     tsvector; mapping is a follow-up).
//   - Value escaping for INSERT rows: single quotes doubled,
//     NULL passed through, numbers unquoted, json strings
//     wrapped + escaped.

export interface TranslationResult {
  pg: string;
  warnings: string[];
}

const SQLITE_TYPE_TO_PG: Record<string, string> = {
  TEXT: 'TEXT',
  INTEGER: 'INTEGER',
  REAL: 'DOUBLE PRECISION',
  BLOB: 'BYTEA',
  NUMERIC: 'NUMERIC',
};

/** Translate a CREATE TABLE / CREATE INDEX / CREATE TRIGGER /
 * CREATE VIRTUAL TABLE etc. statement. The input is a sqlite
 * statement as it appears in db-schema.ts. Output: pg statement
 * (or comment marker for unsupported constructs). */
export function translateCreateStmt(sql: string): TranslationResult {
  const warnings: string[] = [];
  let s = sql;

  // FTS5 virtual tables: pg has its own FTS via tsvector. Emit a
  // comment + leave the actual table out so the rest of the
  // schema still applies cleanly. A follow-up iter wires the
  // pg-native search.
  if (/CREATE\s+VIRTUAL\s+TABLE/i.test(s)) {
    warnings.push(
      'FTS5 virtual table not translated — pg uses tsvector; add manually.',
    );
    return {
      pg: `-- TODO(iter-188): translate FTS5 virtual table to pg tsvector\n-- ${s.replace(/\n/g, ' ').slice(0, 120)}...`,
      warnings,
    };
  }

  // CREATE TRIGGER for FTS sync — same deal, skip.
  if (/CREATE\s+TRIGGER/i.test(s) && /_fts/i.test(s)) {
    warnings.push('FTS sync trigger skipped — replace with pg-native FTS.');
    return {
      pg: `-- TODO(iter-188): pg-native FTS trigger for ${s.match(/TRIGGER\s+IF\s+NOT\s+EXISTS\s+(\w+)/i)?.[1] ?? '?'}`,
      warnings,
    };
  }

  // PRIMARY KEY AUTOINCREMENT → GENERATED BY DEFAULT AS IDENTITY.
  // We can't use SERIAL across the board because the table may
  // already have data with explicit IDs (export+import keeps the
  // existing keys; identity start-value should be max(id)+1
  // which the import script handles separately).
  s = s.replace(
    /(\w+)\s+INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT/gi,
    '$1 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
  );

  // strftime('%Y-%m-%dT%H:%M:%fZ','now') → pg to_char(now()...)
  s = s.replace(
    /strftime\(\s*'%Y-%m-%dT%H:%M:%fZ'\s*,\s*'now'\s*\)/g,
    "to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"')",
  );

  // datetime('now', '-N minutes/hours/days') → now() - interval
  s = s.replace(
    /datetime\(\s*'now'\s*,\s*'-(\d+)\s+(minutes?|hours?|days?|seconds?)'\s*\)/g,
    "now() - interval '$1 $2'",
  );
  s = s.replace(
    /datetime\(\s*'now'\s*\)/g,
    'now()',
  );

  // CREATE INDEX IF NOT EXISTS — pg has the same syntax. Passthrough.

  return { pg: s, warnings };
}

/** Translate a sqlite-side ALTER TABLE ADD COLUMN to pg. SQLite
 * accepts "ALTER TABLE t ADD COLUMN c TYPE ..." which pg supports
 * via "ALTER TABLE t ADD COLUMN IF NOT EXISTS c TYPE ..." (since
 * pg 9.6). Inserts IF NOT EXISTS for idempotency. */
export function translateAlterAddColumn(sql: string): TranslationResult {
  const warnings: string[] = [];
  // Match: ALTER TABLE <name> ADD COLUMN <col> <typespec>
  const m = sql.match(
    /^ALTER\s+TABLE\s+(\w+)\s+ADD\s+COLUMN\s+(\w+)\s+(.+?);?\s*$/i,
  );
  if (!m) {
    return { pg: sql, warnings: ['ALTER pattern unrecognized; passthrough'] };
  }
  const [, table, col, typespec] = m;
  return {
    pg: `ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS ${col} ${typespec};`,
    warnings,
  };
}

/** Escape a JS value for use in a pg literal. NULLs pass through;
 * numbers are unquoted; strings are single-quoted with internal
 * quotes doubled; objects/arrays JSON-stringified then string-quoted. */
export function escapePostgresValue(v: unknown): string {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') {
    if (!Number.isFinite(v)) return 'NULL';
    return String(v);
  }
  if (typeof v === 'boolean') return v ? '1' : '0';
  if (typeof v === 'bigint') return String(v);
  if (typeof v === 'object') {
    return escapePostgresValue(JSON.stringify(v));
  }
  // string
  const str = String(v);
  // pg-standard single-quote escape: double the quote.
  return `'${str.replace(/'/g, "''")}'`;
}

/** Build a pg INSERT statement for one row. table is the sqlite
 * table name; row is the column-keyed object from a SELECT * query.
 * Used by the export script row-by-row. */
export function rowToInsert(
  table: string,
  row: Record<string, unknown>,
): string {
  const cols = Object.keys(row);
  if (cols.length === 0) return '';
  const colList = cols.map((c) => `"${c}"`).join(', ');
  const valList = cols.map((c) => escapePostgresValue(row[c])).join(', ');
  return `INSERT INTO "${table}" (${colList}) VALUES (${valList});`;
}

/** Bulk: emit a multi-row INSERT for performance (pg accepts
 * VALUES (...), (...), ... in one statement). batchSize caps how
 * many rows per statement so a 50k-row table doesn't produce one
 * gigantic SQL string. */
export function rowsToInsertBatch(
  table: string,
  rows: Array<Record<string, unknown>>,
): string {
  if (rows.length === 0) return '';
  const cols = Object.keys(rows[0]!);
  const colList = cols.map((c) => `"${c}"`).join(', ');
  const valGroups = rows
    .map((r) => {
      const vals = cols.map((c) => escapePostgresValue(r[c])).join(', ');
      return `(${vals})`;
    })
    .join(',\n  ');
  return `INSERT INTO "${table}" (${colList}) VALUES\n  ${valGroups};`;
}

/** After bulk INSERTs of AUTOINCREMENT-keyed tables, the pg
 * IDENTITY sequence needs to advance past the highest imported
 * id, or the next INSERT will hit a duplicate-PK error. Returns
 * the SETVAL statement. */
export function resetSequenceForTable(
  table: string,
  pkCol: string,
): string {
  return `SELECT setval(pg_get_serial_sequence('"${table}"', '${pkCol}'), COALESCE((SELECT MAX("${pkCol}") FROM "${table}"), 1));`;
}
