// Iter 184 — Tests for the sqlite → postgres translator.
import { describe, expect, it } from 'vitest';
import {
  escapePostgresValue,
  resetSequenceForTable,
  rowToInsert,
  rowsToInsertBatch,
  translateAlterAddColumn,
  translateCreateStmt,
} from '../src/postgres-export';

describe('translateCreateStmt — types + identity', () => {
  it('converts INTEGER PRIMARY KEY AUTOINCREMENT', () => {
    const sql = `CREATE TABLE IF NOT EXISTS holidays (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL
    )`;
    const { pg } = translateCreateStmt(sql);
    expect(pg).toContain(
      'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    );
    expect(pg).not.toContain('AUTOINCREMENT');
  });

  it('passes through plain CREATE INDEX', () => {
    const sql =
      'CREATE INDEX IF NOT EXISTS idx_foo ON bar(baz) WHERE baz IS NOT NULL';
    const { pg } = translateCreateStmt(sql);
    expect(pg).toBe(sql);
  });
});

describe('translateCreateStmt — date/time fns', () => {
  it('rewrites strftime ISO-Z to to_char', () => {
    const sql = `CREATE TABLE x (created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')))`;
    const { pg } = translateCreateStmt(sql);
    expect(pg).toContain("to_char(now() AT TIME ZONE 'UTC'");
    expect(pg).toContain('YYYY-MM-DD');
    expect(pg).not.toContain('strftime');
  });

  it('rewrites datetime(now, "-30 minutes")', () => {
    const sql = `SELECT * FROM t WHERE ts < datetime('now', '-30 minutes')`;
    const { pg } = translateCreateStmt(sql);
    expect(pg).toContain("now() - interval '30 minutes'");
    expect(pg).not.toContain('datetime');
  });

  it('rewrites datetime(now) alone', () => {
    const sql = `INSERT INTO t (ts) VALUES (datetime('now'))`;
    const { pg } = translateCreateStmt(sql);
    expect(pg).toContain('now()');
    expect(pg).not.toContain('datetime');
  });
});

describe('translateCreateStmt — unsupported constructs', () => {
  it('flags FTS5 virtual tables for manual translation', () => {
    const sql = `CREATE VIRTUAL TABLE IF NOT EXISTS dial_intents_fts USING fts5(transcript_text, ai_summary)`;
    const { pg, warnings } = translateCreateStmt(sql);
    expect(pg).toMatch(/TODO/);
    expect(warnings.length).toBeGreaterThan(0);
    expect(warnings[0]).toMatch(/FTS5/);
  });

  it('flags FTS sync triggers', () => {
    const sql = `CREATE TRIGGER IF NOT EXISTS dial_intents_fts_insert AFTER INSERT ON dial_intents WHEN new.transcript_text IS NOT NULL BEGIN INSERT INTO dial_intents_fts VALUES (...); END`;
    const { pg, warnings } = translateCreateStmt(sql);
    expect(pg).toMatch(/TODO/);
    expect(warnings[0]).toMatch(/FTS/);
  });
});

describe('translateAlterAddColumn', () => {
  it('adds IF NOT EXISTS for idempotency', () => {
    const sql = 'ALTER TABLE users ADD COLUMN org_id TEXT';
    const { pg } = translateAlterAddColumn(sql);
    expect(pg).toBe('ALTER TABLE users ADD COLUMN IF NOT EXISTS org_id TEXT;');
  });

  it('preserves the full typespec including defaults', () => {
    const sql =
      "ALTER TABLE in_groups ADD COLUMN timezone TEXT NOT NULL DEFAULT 'UTC'";
    const { pg } = translateAlterAddColumn(sql);
    expect(pg).toContain("DEFAULT 'UTC'");
    expect(pg).toContain('NOT NULL');
    expect(pg).toContain('IF NOT EXISTS');
  });

  it('passes through unrecognized statements with a warning', () => {
    const sql = 'UPDATE foo SET bar = 1';
    const { pg, warnings } = translateAlterAddColumn(sql);
    expect(pg).toBe(sql);
    expect(warnings.length).toBeGreaterThan(0);
  });
});

describe('escapePostgresValue', () => {
  it('handles null + undefined', () => {
    expect(escapePostgresValue(null)).toBe('NULL');
    expect(escapePostgresValue(undefined)).toBe('NULL');
  });

  it('passes through finite numbers', () => {
    expect(escapePostgresValue(42)).toBe('42');
    expect(escapePostgresValue(-3.14)).toBe('-3.14');
    expect(escapePostgresValue(0)).toBe('0');
  });

  it('treats non-finite numbers as NULL', () => {
    expect(escapePostgresValue(NaN)).toBe('NULL');
    expect(escapePostgresValue(Infinity)).toBe('NULL');
  });

  it('renders booleans as 0/1 (DialerOS stores them that way)', () => {
    expect(escapePostgresValue(true)).toBe('1');
    expect(escapePostgresValue(false)).toBe('0');
  });

  it('escapes single-quotes by doubling', () => {
    expect(escapePostgresValue("O'Reilly")).toBe("'O''Reilly'");
  });

  it('quotes ordinary strings', () => {
    expect(escapePostgresValue('hello')).toBe("'hello'");
  });

  it('JSON-stringifies objects then quotes', () => {
    expect(escapePostgresValue({ a: 1 })).toBe(`'{"a":1}'`);
  });

  it('handles bigint', () => {
    expect(escapePostgresValue(9007199254740993n)).toBe('9007199254740993');
  });
});

describe('rowToInsert / rowsToInsertBatch', () => {
  it('emits a single-row INSERT with quoted ident', () => {
    const sql = rowToInsert('users', {
      id: 'abc',
      username: 'alice',
      org_id: 'default',
    });
    expect(sql).toBe(
      `INSERT INTO "users" ("id", "username", "org_id") VALUES ('abc', 'alice', 'default');`,
    );
  });

  it('returns empty string on empty row', () => {
    expect(rowToInsert('t', {})).toBe('');
  });

  it('builds a multi-row VALUES batch', () => {
    const sql = rowsToInsertBatch('users', [
      { id: 'a', username: 'alice' },
      { id: 'b', username: 'bob' },
    ]);
    expect(sql).toContain('INSERT INTO "users"');
    expect(sql).toContain("('a', 'alice')");
    expect(sql).toContain("('b', 'bob')");
    // Single statement, comma-separated groups.
    expect(sql.match(/;/g)?.length ?? 0).toBe(1);
  });

  it('returns empty string on empty rows array', () => {
    expect(rowsToInsertBatch('t', [])).toBe('');
  });
});

describe('resetSequenceForTable', () => {
  it('emits a setval pegged to MAX(id)+1', () => {
    const sql = resetSequenceForTable('holidays', 'id');
    expect(sql).toContain('setval');
    expect(sql).toContain(`pg_get_serial_sequence('"holidays"', 'id')`);
    expect(sql).toContain(`MAX("id") FROM "holidays"`);
  });
});
