import type { CarrierRecord } from '@dialeros/control-plane';
import { parseCodecs } from '@dialeros/control-plane';

/**
 * Iter 30 — generate a FreeSWITCH SIP gateway XML config for a carrier
 * row. Pure function: takes the row + decrypted password and returns
 * the XML string. The push helper writes the result to disk + reloads.
 *
 * Naming: `dialeros-<carrier-id>` so we can identify our gateways
 * (vs anything an admin manually drops into FreeSWITCH) and clean up
 * orphans cleanly.
 */
export function gatewayNameFor(carrier: Pick<CarrierRecord, 'id'>): string {
  return `dialeros-${carrier.id}`;
}

export function gatewayFilenameFor(carrier: Pick<CarrierRecord, 'id'>): string {
  // FreeSWITCH only includes *.xml in sip_profiles/external/.
  return `dialeros-${carrier.id}.xml`;
}

interface GatewayInputs {
  carrier: CarrierRecord;
  /** decrypted password — required for digest carriers, ignored for ip-acl */
  digestPassword: string | null;
}

/**
 * Build the XML body. Wraps a single <gateway> in an <include> root
 * which is what FreeSWITCH's mod_sofia expects for files dropped under
 * sip_profiles/external/.
 */
export function gatewayXml({ carrier, digestPassword }: GatewayInputs): string {
  const codecs = parseCodecs(carrier);
  const codecPref = codecs.length > 0 ? codecs.join(',') : 'PCMU,PCMA';
  const gwName = gatewayNameFor(carrier);
  const proxyHostPort =
    carrier.port === 5060
      ? carrier.host
      : `${carrier.host}:${carrier.port}`;

  const isDigest = carrier.auth_mode === 'digest';
  const params: Array<[string, string]> = [
    ['proxy', proxyHostPort],
    // Digest carriers register with the carrier; ip-acl carriers don't
    // (the carrier trusts our IP, no SIP auth round-trip needed).
    ['register', isDigest ? 'true' : 'false'],
    // OPTIONS ping. Many ip-acl-only carriers (VOS3000, FreeSWITCH-as-
    // upstream, some ITSPs) reject unauthenticated OPTIONS, which would
    // mark the gateway DOWN and block originates. Only ping digest
    // carriers, where registration AND OPTIONS are part of the same
    // authenticated SIP flow.
    ...(isDigest
      ? ([['ping', '30']] as Array<[string, string]>)
      : ([] as Array<[string, string]>)),
    ['codec-prefs', codecPref],
    ['transport', carrier.transport.toLowerCase()],
  ];

  if (isDigest) {
    if (!carrier.digest_username) {
      throw new Error(
        `Carrier ${carrier.id} is auth_mode=digest but has no username.`,
      );
    }
    if (!digestPassword) {
      throw new Error(
        `Carrier ${carrier.id} is auth_mode=digest but its password could not be decrypted.`,
      );
    }
    params.unshift(['username', carrier.digest_username]);
    params.unshift(['realm', carrier.host]);
    params.unshift(['password', digestPassword]);
  }

  const paramLines = params
    .map(([k, v]) => `    <param name=${attr(k)} value=${attr(v)}/>`)
    .join('\n');

  return [
    `<include>`,
    `  <!-- Generated by DialerOS for carrier ${carrier.id} (${carrier.name}). Do not edit. -->`,
    `  <gateway name=${attr(gwName)}>`,
    paramLines,
    `    <variables>`,
    `      <variable name="dialeros_carrier_id" value=${attr(carrier.id)} direction="inbound"/>`,
    `    </variables>`,
    `  </gateway>`,
    `</include>`,
    ``,
  ].join('\n');
}

function attr(s: string): string {
  // Minimal XML attribute escape. Carrier names + IDs are constrained
  // by the schema (no quotes / angle brackets), but passwords are
  // user-supplied — escape them properly.
  const escaped = s
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
  return `"${escaped}"`;
}
