#!/usr/bin/env bash
#
# Iter 145 — bootstrap /etc/dialeros/admin.env.
#
# The env file holds the shared secret (KAMAILIO_INBOUND_TOKEN) that
# token-gated internal endpoints check, plus operator-tweakable
# values like DIALEROS_REPORT_TO. systemd units load it via
# EnvironmentFile=-/etc/dialeros/admin.env (the leading "-" so a
# missing file isn't a hard failure).
#
# Without this file, ALL of:
#   - dialeros-ai-worker.timer       (iter 137 — AI transcription/summary)
#   - dialeros-daily-report.timer    (iter 131 — nightly email)
#   - dialeros-backup.timer          (iter 112 — sqlite snapshots)
#   - dialeros-prune-recordings.timer (iter 144 — recording retention)
# silently no-op because the X-Inbound-Token comparison in the
# token-gated endpoints fails (process.env.KAMAILIO_INBOUND_TOKEN
# resolves to undefined and the script's curl gets 401).
#
# Idempotent: if admin.env already exists with a KAMAILIO_INBOUND_TOKEN
# line, the existing token is preserved. Re-running this script is
# safe and never rotates an existing token (use --rotate to force).
#
# Run as root.

set -euo pipefail

ETC_DIR=/etc/dialeros
ENV_FILE="${ETC_DIR}/admin.env"
ROTATE=false

for arg in "$@"; do
  case "$arg" in
    --rotate)
      ROTATE=true
      ;;
    -h|--help)
      cat <<'USAGE'
Usage: bootstrap-admin-env.sh [--rotate]

  --rotate   Force a new KAMAILIO_INBOUND_TOKEN. Existing token is
             overwritten. Without this flag, an existing token is
             preserved so the script can re-run safely.

Creates /etc/dialeros/admin.env with:
  - KAMAILIO_INBOUND_TOKEN  (32-byte hex secret)
  - DIALEROS_ADMIN_URL      (http://127.0.0.1:1111)
  - DIALEROS_REPORT_TO      (placeholder — set this to the operator
                             address before enabling the daily report)

Perms: 0640 owned by root:dialeros so the dialeros user can read it
and the admin systemd unit (running as dialeros) inherits the env.
USAGE
      exit 0
      ;;
    *)
      echo "unknown arg: $arg" >&2
      exit 2
      ;;
  esac
done

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: must run as root" >&2
  exit 1
fi

# Ensure /etc/dialeros exists with reasonable perms.
mkdir -p "${ETC_DIR}"
# 0750 so root + dialeros group can traverse, world cannot peek.
chgrp dialeros "${ETC_DIR}" || true
chmod 0750 "${ETC_DIR}"

# Decide on the token.
EXISTING_TOKEN=""
if [ -f "${ENV_FILE}" ]; then
  EXISTING_TOKEN=$(grep -E '^KAMAILIO_INBOUND_TOKEN=' "${ENV_FILE}" | head -1 | cut -d= -f2- | tr -d '"' || true)
fi

if [ -n "${EXISTING_TOKEN}" ] && [ "${ROTATE}" = false ]; then
  TOKEN="${EXISTING_TOKEN}"
  echo "bootstrap-admin-env: existing KAMAILIO_INBOUND_TOKEN preserved (use --rotate to regenerate)"
else
  # 32 bytes of openssl rand, hex-encoded -> 64 chars. Fits well
  # within HTTP header limits and beats anything brute-forceable.
  TOKEN=$(openssl rand -hex 32)
  if [ "${ROTATE}" = true ]; then
    echo "bootstrap-admin-env: NEW KAMAILIO_INBOUND_TOKEN generated (rotate)"
  else
    echo "bootstrap-admin-env: NEW KAMAILIO_INBOUND_TOKEN generated"
  fi
fi

# Preserve other values if present (the operator may have set
# DIALEROS_REPORT_TO etc. manually after a previous run).
EXISTING_REPORT_TO=""
EXISTING_ADMIN_URL=""
if [ -f "${ENV_FILE}" ]; then
  EXISTING_REPORT_TO=$(grep -E '^DIALEROS_REPORT_TO=' "${ENV_FILE}" | head -1 | cut -d= -f2- | tr -d '"' || true)
  EXISTING_ADMIN_URL=$(grep -E '^DIALEROS_ADMIN_URL=' "${ENV_FILE}" | head -1 | cut -d= -f2- | tr -d '"' || true)
fi
ADMIN_URL="${EXISTING_ADMIN_URL:-http://127.0.0.1:1111}"
REPORT_TO="${EXISTING_REPORT_TO:-operator@example.invalid}"

# Atomic write — tempfile + rename so the in-flight write can't be
# read half-finished by a concurrent systemd unit firing.
TMP=$(mktemp -p "${ETC_DIR}" admin.env.XXXXXX)
chmod 0640 "${TMP}"
chgrp dialeros "${TMP}" || true
cat > "${TMP}" <<EOF
# /etc/dialeros/admin.env — loaded by every DialerOS systemd unit
# via EnvironmentFile=-/etc/dialeros/admin.env.
#
# Generated by scripts/bootstrap-admin-env.sh. Re-running that
# script is safe and preserves the existing token (use --rotate
# to force a new one).
#
# Anything added here also becomes process.env.* in the admin
# service since dialeros-admin.service loads this file too.

# Shared secret for token-gated internal endpoints
# (/api/internal/*). The dialeros-admin process compares against
# process.env.KAMAILIO_INBOUND_TOKEN; every script that calls one
# of those endpoints sends X-Inbound-Token: \$KAMAILIO_INBOUND_TOKEN.
KAMAILIO_INBOUND_TOKEN=${TOKEN}

# Where scripts curl the admin process. Default points at the
# local box; change if running scripts on a separate machine.
DIALEROS_ADMIN_URL=${ADMIN_URL}

# Recipient for the iter-131 daily summary email. Set this to a
# real address before enabling dialeros-daily-report.timer.
DIALEROS_REPORT_TO=${REPORT_TO}
EOF
mv -f "${TMP}" "${ENV_FILE}"
chmod 0640 "${ENV_FILE}"
chgrp dialeros "${ENV_FILE}" || true

echo "bootstrap-admin-env: wrote ${ENV_FILE}"
echo "  perms: $(stat -c '%a %U:%G' "${ENV_FILE}")"
echo "  DIALEROS_ADMIN_URL=${ADMIN_URL}"
echo "  DIALEROS_REPORT_TO=${REPORT_TO}"
echo "  KAMAILIO_INBOUND_TOKEN=<${#TOKEN}-char secret>"
echo
echo "Next steps:"
echo "  1. Restart dialeros-admin so it picks up the env:"
echo "       systemctl daemon-reload && systemctl restart dialeros-admin"
echo "  2. (Optional) Enable timers that need the token:"
echo "       systemctl enable --now dialeros-ai-worker.timer"
echo "       systemctl enable --now dialeros-backup.timer"
echo "  3. Set DIALEROS_REPORT_TO to a real address before relying on"
echo "     the daily-report timer."
