#!/usr/bin/env bash
# Iter 36 — set up Let's Encrypt + nginx in front of admin-gui
# (port 1111) and FreeSWITCH WebSocket (port 5066). Result: admin
# GUI on https://<domain>/, sip.js connects to wss://<domain>/sip.
#
# Reads the domain from $DIALEROS_DOMAIN. Optional contact email
# from $DIALEROS_TLS_EMAIL (else admin@<domain>).
#
# Idempotent — safe to re-run after editing the saved domain.

set -euo pipefail
LOG_PREFIX='[setup-tls]'

log()  { echo "$LOG_PREFIX $*"; }
fail() { echo "$LOG_PREFIX ERROR: $*" >&2; exit 1; }

if [[ "$EUID" -ne 0 ]]; then
  fail "must be run as root (use sudo)"
fi
DOMAIN="${DIALEROS_DOMAIN:-}"
[[ -z "$DOMAIN" ]] && fail "DIALEROS_DOMAIN env var not set"
EMAIL="${DIALEROS_TLS_EMAIL:-admin@${DOMAIN}}"

log "domain=$DOMAIN email=$EMAIL"

# Resolve this server's external IPv4 — FreeSWITCH's ws-binding is on
# the default IP (`:5066`), not 0.0.0.0. nginx therefore can't reach
# FS via 127.0.0.1:5066; it has to use the external interface.
LOCAL_IP="$(ip -4 -o addr show scope global 2>/dev/null \
  | awk '{print $4}' | cut -d/ -f1 | head -n1)"
if [[ -z "$LOCAL_IP" ]]; then
  fail "could not detect external IPv4 — set it manually then re-run"
fi
log "external ip for FS proxy_pass: $LOCAL_IP"

# --- step 1: install nginx + certbot ---
log "installing nginx + certbot"
DEBIAN_FRONTEND=noninteractive apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nginx certbot

# --- step 2: stop nginx for standalone challenge if it's running ---
log "stopping nginx for standalone cert issuance"
systemctl stop nginx 2>/dev/null || true

# --- step 3: get cert ---
if [[ -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]]; then
  log "cert already exists for $DOMAIN; running renew check"
  certbot renew --quiet || log "renew not yet due (ok)"
else
  log "issuing Let's Encrypt cert for $DOMAIN (requires port 80 free)"
  certbot certonly --standalone --non-interactive --agree-tos \
    --no-eff-email --email "$EMAIL" -d "$DOMAIN"
fi

# --- step 4: write nginx site ---
SITE=/etc/nginx/sites-available/dialeros
log "writing $SITE"
cat > "$SITE" <<NGINX
# Generated by DialerOS setup-tls.sh — re-run the script to regenerate.
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    # Lets-encrypt http-01 webroot challenge stays on port 80 so renewals
    # via 'certbot renew' work without taking nginx down again.
    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }
    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    # Note: HTTP/2 deliberately NOT enabled here. nginx <1.25 can't
    # bridge HTTP/2 ↔ WebSocket upgrades (RFC 8441), so sip.js
    # registration over wss://<domain>/sip stalls forever — FS sends
    # back 101 Switching Protocols but nginx never forwards it. Plain
    # HTTPS over HTTP/1.1 works for both the admin GUI and WS path.
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    # SIP-over-WebSocket reverse-proxy → FreeSWITCH. FS binds ws on
    # ${LOCAL_IP}:5066, NOT 127.0.0.1, because the internal profile's
    # ws-binding param is "default-IP only". Match that here.
    # Trailing slash on proxy_pass strips the /sip location prefix so
    # the request reaches FS as path "/" (FS doesn't accept /sip).
    location /sip {
        proxy_pass http://${LOCAL_IP}:5066/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
        proxy_buffering off;
    }

    # Admin GUI + everything else
    location / {
        proxy_pass http://127.0.0.1:1111;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 300s;
    }

    client_max_body_size 16m;
}
NGINX

ln -sf "$SITE" /etc/nginx/sites-enabled/dialeros
rm -f /etc/nginx/sites-enabled/default

mkdir -p /var/www/letsencrypt

# --- step 5: post-renewal hook so nginx reloads when certbot rotates ---
mkdir -p /etc/letsencrypt/renewal-hooks/post
HOOK=/etc/letsencrypt/renewal-hooks/post/dialeros-reload.sh
cat > "$HOOK" <<'HOOK_EOF'
#!/usr/bin/env bash
systemctl reload nginx
HOOK_EOF
chmod 0755 "$HOOK"

# --- step 6: sanity check + start ---
log "nginx -t"
nginx -t

log "starting nginx"
systemctl enable nginx
systemctl start nginx

# Allow the dialeros user (admin-gui process) to traverse the
# letsencrypt tree so /api/settings/domain/tls-status can read the
# expiry from fullchain.pem and softphone-config can detect the
# cert exists. fullchain.pem is mode 644 from certbot already;
# privkey.pem stays 600 (only root reads).
log "opening /etc/letsencrypt traversal for dialeros user"
chmod 0755 /etc/letsencrypt /etc/letsencrypt/live /etc/letsencrypt/archive

# === step 7: copy cert into FreeSWITCH's TLS dir and reload sofia ===
#
# We can't proxy SIP-over-WebSocket through nginx because nginx
# terminates TLS, but the browser's sip.js sets Via: SIP/2.0/WSS in
# the SIP message (because the WS transport IS WSS from sip.js's
# point of view). FS sees Via:WSS arriving over a plain WS socket
# and silently drops the request — transport mismatch.
#
# So the browser instead connects DIRECTLY to FS's wss-binding on
# port 7443. FS already has wss-binding=:7443; we just need to give
# it our real Let's Encrypt cert (it ships with a self-signed one
# that browsers refuse). FS expects /etc/freeswitch/tls/wss.pem to
# contain the private key + full chain concatenated.
log "installing Let's Encrypt cert into FreeSWITCH (/etc/freeswitch/tls/wss.pem)"
mkdir -p /etc/freeswitch/tls
cat \
  /etc/letsencrypt/live/${DOMAIN}/privkey.pem \
  /etc/letsencrypt/live/${DOMAIN}/fullchain.pem \
  > /etc/freeswitch/tls/wss.pem
chown freeswitch:freeswitch /etc/freeswitch/tls/wss.pem
chmod 0640 /etc/freeswitch/tls/wss.pem

log "restarting sofia internal profile to pick up new cert"
fs_cli -x "sofia profile internal restart reloadxml" >/dev/null 2>&1 || \
  log "(fs_cli not available — restart freeswitch manually if needed)"

# Renewal hook: on cert rotation, refresh wss.pem and reload sofia.
HOOK=/etc/letsencrypt/renewal-hooks/post/dialeros-fs-cert.sh
cat > "$HOOK" <<HOOK_EOF
#!/usr/bin/env bash
cat /etc/letsencrypt/live/${DOMAIN}/privkey.pem \\
    /etc/letsencrypt/live/${DOMAIN}/fullchain.pem \\
  > /etc/freeswitch/tls/wss.pem
chown freeswitch:freeswitch /etc/freeswitch/tls/wss.pem
chmod 0640 /etc/freeswitch/tls/wss.pem
fs_cli -x "sofia profile internal restart reloadxml" >/dev/null 2>&1 || true
HOOK_EOF
chmod 0755 "$HOOK"

log "done. admin GUI:  https://${DOMAIN}/"
log "softphone WSS:    wss://${DOMAIN}:7443/  (direct to FreeSWITCH)"
