#!/usr/bin/env bash
# Iter 36 — set up Let's Encrypt + nginx in front of admin-gui
# (port 1111) and FreeSWITCH WebSocket (port 5066). Result: admin
# GUI on https://<domain>/, sip.js connects to wss://<domain>/sip.
#
# Reads the domain from $DIALEROS_DOMAIN. Optional contact email
# from $DIALEROS_TLS_EMAIL (else admin@<domain>).
#
# Idempotent — safe to re-run after editing the saved domain.

set -euo pipefail
LOG_PREFIX='[setup-tls]'

log()  { echo "$LOG_PREFIX $*"; }
fail() { echo "$LOG_PREFIX ERROR: $*" >&2; exit 1; }

if [[ "$EUID" -ne 0 ]]; then
  fail "must be run as root (use sudo)"
fi
DOMAIN="${DIALEROS_DOMAIN:-}"
[[ -z "$DOMAIN" ]] && fail "DIALEROS_DOMAIN env var not set"
EMAIL="${DIALEROS_TLS_EMAIL:-admin@${DOMAIN}}"

log "domain=$DOMAIN email=$EMAIL"

# --- step 1: install nginx + certbot ---
log "installing nginx + certbot"
DEBIAN_FRONTEND=noninteractive apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nginx certbot

# --- step 2: stop nginx for standalone challenge if it's running ---
log "stopping nginx for standalone cert issuance"
systemctl stop nginx 2>/dev/null || true

# --- step 3: get cert ---
if [[ -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]]; then
  log "cert already exists for $DOMAIN; running renew check"
  certbot renew --quiet || log "renew not yet due (ok)"
else
  log "issuing Let's Encrypt cert for $DOMAIN (requires port 80 free)"
  certbot certonly --standalone --non-interactive --agree-tos \
    --no-eff-email --email "$EMAIL" -d "$DOMAIN"
fi

# --- step 4: write nginx site ---
SITE=/etc/nginx/sites-available/dialeros
log "writing $SITE"
cat > "$SITE" <<NGINX
# Generated by DialerOS setup-tls.sh — re-run the script to regenerate.
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    # Lets-encrypt http-01 webroot challenge stays on port 80 so renewals
    # via 'certbot renew' work without taking nginx down again.
    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }
    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    # SIP-over-WebSocket reverse-proxy → FreeSWITCH
    location /sip {
        proxy_pass http://127.0.0.1:5066;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
        proxy_buffering off;
    }

    # Admin GUI + everything else
    location / {
        proxy_pass http://127.0.0.1:1111;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 300s;
    }

    client_max_body_size 16m;
}
NGINX

ln -sf "$SITE" /etc/nginx/sites-enabled/dialeros
rm -f /etc/nginx/sites-enabled/default

mkdir -p /var/www/letsencrypt

# --- step 5: post-renewal hook so nginx reloads when certbot rotates ---
mkdir -p /etc/letsencrypt/renewal-hooks/post
HOOK=/etc/letsencrypt/renewal-hooks/post/dialeros-reload.sh
cat > "$HOOK" <<'HOOK_EOF'
#!/usr/bin/env bash
systemctl reload nginx
HOOK_EOF
chmod 0755 "$HOOK"

# --- step 6: sanity check + start ---
log "nginx -t"
nginx -t

log "starting nginx"
systemctl enable nginx
systemctl start nginx

log "done. admin GUI: https://${DOMAIN}/"
log "softphone WSS: wss://${DOMAIN}/sip"
